# target variable : tip

In [1]:
!cd

In [1]:
import pymysql.cursors
# Connect to the database
import pandas as pd
import numpy as np

In [3]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost',
        user='yoohwayoung',
        password='00000000',
        db='tip',
        charset='utf8',
        autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "SELECT * FROM tips; "
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
#    df.to_csv('query.csv')
    

    
finally:

   conn.close()

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
257       22.00  5.00    Male     No  Sat  Dinner     4
258       29.00  5.00    Male     No  Sat  Dinner     4
259       39.00  5.00    Male     No  Sat  Dinner     4
260       17.00  5.00    Male    Yes  Sat  Dinner     4
261       33.00  6.00  Female    Yes  Sat  Dinner     4

[262 rows x 7 columns]


In [2]:
url = 'https://raw.githubusercontent.com/JSJeong-me/2021-K-Digital-Training/main/Python/pandas/tips.csv'
df = pd.read_csv(url)

In [3]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.isnull().sum() #null값 전처리 -> 어떻게 하냐? 연구주제

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [5]:
df['tip_rate'] = df['tip'] / df['total_bill'] #파생변수
df.head(3)

total_bill   tip     sex smoker  day    time  size  tip_rate
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587

In [8]:
df['sex'].replace({'Female':0, 'Male':1}, inplace=True)#바이너리인코딩 -> 원핫인코딩
df['smoker'].replace({'No':0, 'Yes':1}, inplace=True)#바이너리인코딩
df['time'].replace({'Lunch':0, 'Dinner':1}, inplace=True)#바이너리인코딩
df['day'].replace({'Thur':0, 'Fri':1, 'Sat':2, 'Sun':3}, inplace=True) #라벨인코딩

In [9]:
df.replace('',np.nan,inplace=True) # '' -> np.nan

In [10]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  244.000000  244.000000  244.000000  244.000000  244.000000  244.000000   
mean    19.785943    2.998279    0.643443    0.381148    1.725410    0.721311   
std      8.902412    1.383638    0.479967    0.486667    1.155774    0.449276   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.347500    2.000000    0.000000    0.000000    0.000000    0.000000   
50%     17.795000    2.900000    1.000000    0.000000    2.000000    1.000000   
75%     24.127500    3.562500    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  244.000000  244.000000  
mean     2.569672    0.160803  
std      0.951100    0.061072  
min      1.000000    0.035638  
25%      2.000000    0.129127  
50%      2.000000    0.154770  
75%      3.000000    0.191475  
max      6.000000    0.710345

In [11]:
df.info() #모든 타입이 object가 아니어야함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    int64  
 3   smoker      244 non-null    int64  
 4   day         244 non-null    int64  
 5   time        244 non-null    int64  
 6   size        244 non-null    int64  
 7   tip_rate    244 non-null    float64
dtypes: float64(3), int64(5)
memory usage: 15.4 KB


In [12]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
tip_rate      0
dtype: int64

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
import pandas as pd
import numpy as np
from numpy import isnan
from sklearn.impute import SimpleImputer

In [17]:
df.head()

total_bill   tip  sex  smoker  day  time  size  tip_rate
0       16.99  1.01    0       0    3     1     2  0.059447
1       10.34  1.66    1       0    3     1     3  0.160542
2       21.01  3.50    1       0    3     1     3  0.166587
3       23.68  3.31    1       0    3     1     2  0.139780
4       24.59  3.61    0       0    3     1     4  0.146808

In [16]:
data = df.values
data

array([[16.99      ,  1.01      ,  0.        , ...,  1.        ,
         2.        ,  0.05944673],
       [10.34      ,  1.66      ,  1.        , ...,  1.        ,
         3.        ,  0.16054159],
       [21.01      ,  3.5       ,  1.        , ...,  1.        ,
         3.        ,  0.16658734],
       ...,
       [22.67      ,  2.        ,  1.        , ...,  1.        ,
         2.        ,  0.08822232],
       [17.82      ,  1.75      ,  1.        , ...,  1.        ,
         2.        ,  0.09820426],
       [18.78      ,  3.        ,  0.        , ...,  1.        ,
         2.        ,  0.15974441]])

In [15]:
#sum(np.isnan(data).flatten) 
# 또는 #df.replace(to_replace=[None], value=np.nan, inplace=True)

In [21]:
y=df['tip'] #x,y를 갈라주는작업 => tip : 목표변수

In [22]:
X=df.drop('tip',axis=1) #tip은 목표변수니까

In [23]:
X.describe() #tip이 빠졌음!! 이 작업을 진행한 것임

tip         sex      smoker         day        time        size  \
count  244.000000  244.000000  244.000000  244.000000  244.000000  244.000000   
mean     2.998279    0.643443    0.381148    1.725410    0.721311    2.569672   
std      1.383638    0.479967    0.486667    1.155774    0.449276    0.951100   
min      1.000000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%      2.000000    0.000000    0.000000    0.000000    0.000000    2.000000   
50%      2.900000    1.000000    0.000000    2.000000    1.000000    2.000000   
75%      3.562500    1.000000    1.000000    3.000000    1.000000    3.000000   
max     10.000000    1.000000    1.000000    3.000000    1.000000    6.000000   

         tip_rate  
count  244.000000  
mean     0.160803  
std      0.061072  
min      0.035638  
25%      0.129127  
50%      0.154770  
75%      0.191475  
max      0.710345

In [24]:
y.describe()

count    244.000000
mean      19.785943
std        8.902412
min        3.070000
25%       13.347500
50%       17.795000
75%       24.127500
max       50.810000
Name: total_bill, dtype: float64

In [25]:
data=X.values
data

array([[1.01      , 0.        , 0.        , ..., 1.        , 2.        ,
        0.05944673],
       [1.66      , 1.        , 0.        , ..., 1.        , 3.        ,
        0.16054159],
       [3.5       , 1.        , 0.        , ..., 1.        , 3.        ,
        0.16658734],
       ...,
       [2.        , 1.        , 1.        , ..., 1.        , 2.        ,
        0.08822232],
       [1.75      , 1.        , 0.        , ..., 1.        , 2.        ,
        0.09820426],
       [3.        , 0.        , 0.        , ..., 1.        , 2.        ,
        0.15974441]])

In [26]:
y=y.values
y

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52,

In [22]:
X.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [27]:
data[:,4]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [28]:
sum(np.isnan(data).flatten())

0

In [29]:
sum(np.isnan(y).flatten())

0

In [30]:
imputer = SimpleImputer(strategy='median') #strategy='most_frequent' #카테고리형 변수는 중앙값이나 최빈값으로 채우기

In [32]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [33]:
# transform the dataset
data_trans = imputer.transform(data)

## RFE (Recursive Feature Elimination)

In [34]:
# from sklearn.datasets import make_classification
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVR

In [36]:
estimator=SVR(kernel='linear') #estimator => 방법
estimator

SVR(kernel='linear')

In [37]:
# define RFE
rfe = RFE(estimator, n_features_to_select=4) #4개 변수 추출

In [38]:
# fit RFE
selector=rfe.fit(data_trans,y)
#rfe.fit(X, y)

In [39]:
selector.support_

array([ True, False,  True, False, False,  True,  True])

In [40]:
df

total_bill   tip  sex  smoker  day  time  size  tip_rate
0         16.99  1.01    0       0    3     1     2  0.059447
1         10.34  1.66    1       0    3     1     3  0.160542
2         21.01  3.50    1       0    3     1     3  0.166587
3         23.68  3.31    1       0    3     1     2  0.139780
4         24.59  3.61    0       0    3     1     4  0.146808
..          ...   ...  ...     ...  ...   ...   ...       ...
239       29.03  5.92    1       0    2     1     3  0.203927
240       27.18  2.00    0       1    2     1     2  0.073584
241       22.67  2.00    1       1    2     1     2  0.088222
242       17.82  1.75    1       0    2     1     2  0.098204
243       18.78  3.00    0       0    0     1     2  0.159744

[244 rows x 8 columns]

In [41]:
# summarize all features
for i in range(data_trans.shape[1]):
  print('Column: %d, Selected=%s, Rank: %d' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected=True, Rank: 1
Column: 1, Selected=False, Rank: 4
Column: 2, Selected=True, Rank: 1
Column: 3, Selected=False, Rank: 3
Column: 4, Selected=False, Rank: 2
Column: 5, Selected=True, Rank: 1
Column: 6, Selected=True, Rank: 1


In [43]:
df1=pd.DataFrame(data_trans, columns=['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'])

In [44]:
df1.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [77]:
# df1.columns(['day','time'], axis=1)

In [45]:
df_trans = pd.DataFrame(data_trans)

In [46]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [47]:
df_trans

0    1    2    3    4    5         6
0    1.01  0.0  0.0  3.0  1.0  2.0  0.059447
1    1.66  1.0  0.0  3.0  1.0  3.0  0.160542
2    3.50  1.0  0.0  3.0  1.0  3.0  0.166587
3    3.31  1.0  0.0  3.0  1.0  2.0  0.139780
4    3.61  0.0  0.0  3.0  1.0  4.0  0.146808
..    ...  ...  ...  ...  ...  ...       ...
239  5.92  1.0  0.0  2.0  1.0  3.0  0.203927
240  2.00  0.0  1.0  2.0  1.0  2.0  0.073584
241  2.00  1.0  1.0  2.0  1.0  2.0  0.088222
242  1.75  1.0  0.0  2.0  1.0  2.0  0.098204
243  3.00  0.0  0.0  0.0  1.0  2.0  0.159744

[244 rows x 7 columns]

## MinMaxScaler

In [48]:
# example of normalizing input data
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler  #Nomalization 호출

In [52]:
trans=MinMaxScaler()

In [53]:
data.shape

(244, 7)

In [54]:
X_norm=trans.fit_transform(data)

In [55]:
df_norm=pd.DataFrame(X_norm)

In [56]:
#Nomalization 확인
df_norm.describe() #값이 0과 1

0           1           2           3           4           5  \
count  244.000000  244.000000  244.000000  244.000000  244.000000  244.000000   
mean     0.222031    0.643443    0.381148    0.575137    0.721311    0.313934   
std      0.153738    0.479967    0.486667    0.385258    0.449276    0.190220   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.111111    0.000000    0.000000    0.000000    0.000000    0.200000   
50%      0.211111    1.000000    0.000000    0.666667    1.000000    0.200000   
75%      0.284722    1.000000    1.000000    1.000000    1.000000    0.400000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                6  
count  244.000000  
mean     0.185509  
std      0.090517  
min      0.000000  
25%      0.138563  
50%      0.176568  
75%      0.230971  
max      1.000000

In [57]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  244.000000  244.000000  244.000000  244.000000  244.000000  244.000000   
mean    19.785943    2.998279    0.643443    0.381148    1.725410    0.721311   
std      8.902412    1.383638    0.479967    0.486667    1.155774    0.449276   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.347500    2.000000    0.000000    0.000000    0.000000    0.000000   
50%     17.795000    2.900000    1.000000    0.000000    2.000000    1.000000   
75%     24.127500    3.562500    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  244.000000  244.000000  
mean     2.569672    0.160803  
std      0.951100    0.061072  
min      1.000000    0.035638  
25%      2.000000    0.129127  
50%      2.000000    0.154770  
75%      3.000000    0.191475  
max      6.000000    0.710345

## StandardScaler

In [58]:
from sklearn.preprocessing import StandardScaler #Standardization 호출

In [59]:
sc = StandardScaler()


In [60]:
df_sc = sc.fit_transform(data)

In [61]:
df_transform_sc=pd.DataFrame(df_sc)

In [62]:
df_transform_sc.describe().round() #평균이 0, 분산이 1로 바뀜

0      1      2      3      4      5      6
count  244.0  244.0  244.0  244.0  244.0  244.0  244.0
mean     0.0   -0.0    0.0    0.0    0.0   -0.0   -0.0
std      1.0    1.0    1.0    1.0    1.0    1.0    1.0
min     -1.0   -1.0   -1.0   -1.0   -2.0   -2.0   -2.0
25%     -1.0   -1.0   -1.0   -1.0   -2.0   -1.0   -1.0
50%     -0.0    1.0   -1.0    0.0    1.0   -1.0   -0.0
75%      0.0    1.0    1.0    1.0    1.0    0.0    1.0
max      5.0    1.0    1.0    1.0    1.0    4.0    9.0

## PCA

In [63]:
# define the transform #PCA는 목표변수 설정이 필요하지 않음
from sklearn.decomposition import PCA

In [64]:
data_trans.shape

(244, 7)

In [69]:
trans = PCA(n_components=2)

# transform the data
X_dim = trans.fit_transform(data_trans)

# summarize data after the transform
print(X_dim[:5, :])

[[-1.5111778  -1.86994442]
 [-0.4870626  -1.6613889 ]
 [ 1.05953329 -1.0418941 ]
 [ 0.47564314 -1.18300591]
 [ 1.52284107 -0.84012251]]


In [70]:
df_X_dim=pd.DataFrame(X_dim)

In [71]:
df_X_dim.describe().round()

0      1
count  244.0  244.0
mean     0.0    0.0
std      2.0    1.0
min     -2.0   -2.0
25%     -1.0   -1.0
50%     -0.0   -0.0
75%      1.0    1.0
max      6.0    3.0

## Regression Feature Selection:

In [82]:
# define feature selection 선택 종류와 개수 설정
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [83]:
fs = SelectKBest(score_func=f_regression, k=4)

In [84]:
# apply feature selection
X_selected = fs.fit_transform(data_trans, y)
print(X_selected.shape)

(262, 4)


In [85]:
df_X_selected = pd.DataFrame(X_selected)

In [86]:
df_X_selected.describe()

0           1           2           3
count  262.000000  262.000000  262.000000  262.000000
mean    19.589771    1.744275    2.599237    0.173595
std      9.302238    1.117377    0.980499    0.107647
min      2.360000    0.000000    1.000000    0.035638
25%     13.137500    1.000000    2.000000    0.129616
50%     17.795000    2.000000    2.000000    0.156661
75%     24.457500    3.000000    3.000000    0.194900
max     50.810000    3.000000    6.000000    1.271186