# target variable : tip

In [1]:
!cd

In [2]:
import pymysql.cursors
# Connect to the database
import pandas as pd
import numpy as np

In [3]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost',
        user='yoohwayoung',
        password='00000000',
        db='tip',
        charset='utf8',
        autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "SELECT * FROM tips; "
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
#    df.to_csv('query.csv')
    

    
finally:

   conn.close()

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
257       22.00  5.00    Male     No  Sat  Dinner     4
258       29.00  5.00    Male     No  Sat  Dinner     4
259       39.00  5.00    Male     No  Sat  Dinner     4
260       17.00  5.00    Male    Yes  Sat  Dinner     4
261       33.00  6.00  Female    Yes  Sat  Dinner     4

[262 rows x 7 columns]


In [4]:
df

total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
257       22.00  5.00    Male     No  Sat  Dinner     4
258       29.00  5.00    Male     No  Sat  Dinner     4
259       39.00  5.00    Male     No  Sat  Dinner     4
260       17.00  5.00    Male    Yes  Sat  Dinner     4
261       33.00  6.00  Female    Yes  Sat  Dinner     4

[262 rows x 7 columns]

In [5]:
df.isnull().sum() #=> null값 확인 , 전처리 어떻게 했는지

total_bill    0
tip           0
sex           5
smoker        0
day           1
time          1
size          0
dtype: int64

In [6]:
df['tip_rate'] = df['tip'] / df['total_bill'] #파생변수
df.head(3)

total_bill   tip     sex smoker  day    time  size  tip_rate
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587

In [7]:
df['sex'].replace({'Female':0, 'Male':1}, inplace=True)#바이너리인코딩 - > 원핫인코딩 맞으면 0, 틀리면 1 이런식으로
df['smoker'].replace({'No':0, 'Yes':1}, inplace=True)#바이너리인코딩
df['time'].replace({'Lunch':0, 'Dinner':1}, inplace=True)#바이너리인코딩
df['day'].replace({'Thur':0, 'Fri':1, 'Sat':2, 'Sun':3}, inplace=True) #라벨인코딩

#바이너리인코딩할때 무엇을 0으로 하는지 1로할지 지정을 하는것 : 일종의 묶음에 따라 달라질 수 있다.

In [8]:
df.replace('',np.nan,inplace=True) # '' -> np.nan

In [9]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  262.000000  262.000000  257.000000  262.000000  261.000000  261.000000   
mean    19.589771    3.016832    0.645914    0.377863    1.743295    0.739464   
std      9.302238    1.398981    0.479168    0.485781    1.119411    0.439771   
min      2.360000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.137500    2.000000    0.000000    0.000000    1.000000    0.000000   
50%     17.795000    3.000000    1.000000    0.000000    2.000000    1.000000   
75%     24.457500    3.610000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  262.000000  262.000000  
mean     2.599237    0.173595  
std      0.980499    0.107647  
min      1.000000    0.035638  
25%      2.000000    0.129616  
50%      2.000000    0.156661  
75%      3.000000    0.194900  
max      6.000000    1.271186

In [10]:
df.info() #모든 타입이 object가 아니어야함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  262 non-null    float64
 1   tip         262 non-null    float64
 2   sex         257 non-null    float64
 3   smoker      262 non-null    int64  
 4   day         261 non-null    float64
 5   time        261 non-null    float64
 6   size        262 non-null    int64  
 7   tip_rate    262 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 16.5 KB


In [11]:
df.isnull().sum()

total_bill    0
tip           0
sex           5
smoker        0
day           1
time          1
size          0
tip_rate      0
dtype: int64

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
import pandas as pd
import numpy as np
from numpy import isnan
from sklearn.impute import SimpleImputer

In [87]:
df.head()

total_bill   tip  sex  smoker  day  time  size  tip_rate
0       16.99  1.01  0.0       0  3.0   1.0     2  0.059447
1       10.34  1.66  1.0       0  3.0   1.0     3  0.160542
2       21.01  3.50  1.0       0  3.0   1.0     3  0.166587
3       23.68  3.31  1.0       0  3.0   1.0     2  0.139780
4       24.59  3.61  0.0       0  3.0   1.0     4  0.146808

In [88]:
data = df.values
data #한줄씩 어레이로 들어간 것을 확인할 수 있음

array([[16.99      ,  1.01      ,  0.        , ...,  1.        ,
         2.        ,  0.05944673],
       [10.34      ,  1.66      ,  1.        , ...,  1.        ,
         3.        ,  0.16054159],
       [21.01      ,  3.5       ,  1.        , ...,  1.        ,
         3.        ,  0.16658734],
       ...,
       [39.        ,  5.        ,  1.        , ...,  1.        ,
         4.        ,  0.12820513],
       [17.        ,  5.        ,  1.        , ...,  1.        ,
         4.        ,  0.29411765],
       [33.        ,  6.        ,  0.        , ...,  1.        ,
         4.        ,  0.18181818]])

In [15]:
#sum(np.isnan(data).flatten) 
# 또는 #df.replace(to_replace=[None], value=np.nan, inplace=True)

In [16]:
y=df['tip'] #x,y를 갈라주는작업 => tip : 목표변수

In [17]:
X=df.drop('tip',axis=1) #tip은 목표변수니까

In [18]:
X.describe() #tip이 빠졌음!! 이 작업을 진행한 것임

total_bill         sex      smoker         day        time        size  \
count  262.000000  257.000000  262.000000  261.000000  261.000000  262.000000   
mean    19.589771    0.645914    0.377863    1.743295    0.739464    2.599237   
std      9.302238    0.479168    0.485781    1.119411    0.439771    0.980499   
min      2.360000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%     13.137500    0.000000    0.000000    1.000000    0.000000    2.000000   
50%     17.795000    1.000000    0.000000    2.000000    1.000000    2.000000   
75%     24.457500    1.000000    1.000000    3.000000    1.000000    3.000000   
max     50.810000    1.000000    1.000000    3.000000    1.000000    6.000000   

         tip_rate  
count  262.000000  
mean     0.173595  
std      0.107647  
min      0.035638  
25%      0.129616  
50%      0.156661  
75%      0.194900  
max      1.271186

In [19]:
y.describe()

count    262.000000
mean       3.016832
std        1.398981
min        1.000000
25%        2.000000
50%        3.000000
75%        3.610000
max       10.000000
Name: tip, dtype: float64

In [20]:
data=X.values

In [21]:
y=y.values

In [22]:
X.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [23]:
data[:,4]

array([2., 3., 3., 2., 4., 4., 2., 4., 2., 2., 2., 4., 2., 4., 2., 2., 3.,
       3., 3., 3., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 4., 2., 4.,
       2., 3., 3., 3., 3., 3., 3., 2., 2., 2., 4., 2., 2., 4., 3., 2., 2.,
       2., 4., 2., 4., 2., 4., 2., 2., 4., 2., 2., 2., 4., 3., 3., 2., 1.,
       2., 2., 2., 3., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 1., 2., 2.,
       4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 1., 3., 2., 3., 2., 4., 2., 2.,
       4., 2., 2., 2., 2., 2., 6., 2., 2., 2., 3., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 6., 5., 6., 2., 2., 3., 2., 2., 2., 2., 2., 3.,
       4., 4., 5., 6., 4., 2., 4., 4., 2., 3., 2., 2., 3., 2., 4., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 3., 4., 2., 5., 3.,
       5., 3., 3., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 3., 2., 2., 2.,
       4., 3., 3., 4., 2., 2., 3., 4., 4., 2., 3., 2., 5., 2., 2., 4., 2.,
       2., 1., 3., 2., 2.

In [81]:
sum(np.isnan(data).flatten())

0

In [25]:
sum(np.isnan(y).flatten())

0

In [26]:
imputer = SimpleImputer(strategy='median') #strategy='most_frequent' #카테고리형 변수는 중앙값이나 최빈값으로 채우기

In [27]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [28]:
# transform the dataset
data_trans = imputer.transform(data)

## RFE  (Report which features were selected)

In [29]:
# from sklearn.datasets import make_classification
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier => #모델명 : 0과 1일때만 쓸 수 있다. True와 False 
from sklearn.svm import SVR # 이것은 무엇인가?

In [30]:
estimator=SVR(kernel='linear')

In [69]:
# define RFE
rfe = RFE(estimator, n_features_to_select=4)

In [70]:
# fit RFE
selector=rfe.fit(data_trans,y)
#rfe.fit(X, y)

In [71]:
!cd

In [72]:
selector.support_

array([ True, False, False,  True,  True, False,  True])

In [73]:
df

total_bill   tip  sex  smoker  day  time  size  tip_rate
0         16.99  1.01  0.0       0  3.0   1.0     2  0.059447
1         10.34  1.66  1.0       0  3.0   1.0     3  0.160542
2         21.01  3.50  1.0       0  3.0   1.0     3  0.166587
3         23.68  3.31  1.0       0  3.0   1.0     2  0.139780
4         24.59  3.61  0.0       0  3.0   1.0     4  0.146808
..          ...   ...  ...     ...  ...   ...   ...       ...
257       22.00  5.00  1.0       0  2.0   1.0     4  0.227273
258       29.00  5.00  1.0       0  2.0   1.0     4  0.172414
259       39.00  5.00  1.0       0  2.0   1.0     4  0.128205
260       17.00  5.00  1.0       1  2.0   1.0     4  0.294118
261       33.00  6.00  0.0       1  2.0   1.0     4  0.181818

[262 rows x 8 columns]

In [74]:
# summarize all features
for i in range(data_trans.shape[1]):
  print('Column: %d, Selected=%s, Rank: %d' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected=True, Rank: 1
Column: 1, Selected=False, Rank: 3
Column: 2, Selected=False, Rank: 4
Column: 3, Selected=True, Rank: 1
Column: 4, Selected=True, Rank: 1
Column: 5, Selected=False, Rank: 2
Column: 6, Selected=True, Rank: 1


In [75]:
df1=pd.DataFrame(data_trans, columns=['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'])

In [76]:
df1.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [77]:
# df1.columns(['day','time'], axis=1)

In [78]:
df_trans = pd.DataFrame(data_trans)

In [79]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [80]:
df_trans

0    1    2    3    4    5         6
0    16.99  0.0  0.0  3.0  1.0  2.0  0.059447
1    10.34  1.0  0.0  3.0  1.0  3.0  0.160542
2    21.01  1.0  0.0  3.0  1.0  3.0  0.166587
3    23.68  1.0  0.0  3.0  1.0  2.0  0.139780
4    24.59  0.0  0.0  3.0  1.0  4.0  0.146808
..     ...  ...  ...  ...  ...  ...       ...
257  22.00  1.0  0.0  2.0  1.0  4.0  0.227273
258  29.00  1.0  0.0  2.0  1.0  4.0  0.172414
259  39.00  1.0  0.0  2.0  1.0  4.0  0.128205
260  17.00  1.0  1.0  2.0  1.0  4.0  0.294118
261  33.00  0.0  1.0  2.0  1.0  4.0  0.181818

[262 rows x 7 columns]

## MinMaxScaler

---------------------------
min-max: 범주의 통일 -> total_bill 금액: 큼 / sex : 0,1
-standard : 데이터가 이미 한 범주 -> 같은 기준으로 정렬(똑같은 mean, var)

In [44]:
# example of normalizing input data # 전체값을 0과 1사이로 만드는 것이 핵심
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler

In [45]:
trans=MinMaxScaler()

In [46]:
data.shape

(262, 7)

In [47]:
X_norm=trans.fit_transform(data)

In [48]:
df_norm=pd.DataFrame(X_norm)

In [49]:
df_norm.describe()

0           1           2           3           4           5  \
count  262.000000  257.000000  262.000000  261.000000  261.000000  262.000000   
mean     0.355620    0.645914    0.377863    0.581098    0.739464    0.319847   
std      0.191997    0.479168    0.485781    0.373137    0.439771    0.196100   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.222446    0.000000    0.000000    0.333333    0.000000    0.200000   
50%      0.318576    1.000000    0.000000    0.666667    1.000000    0.200000   
75%      0.456089    1.000000    1.000000    1.000000    1.000000    0.400000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                6  
count  262.000000  
mean     0.111656  
std      0.087125  
min      0.000000  
25%      0.076062  
50%      0.097951  
75%      0.128900  
max      1.000000

In [50]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  262.000000  262.000000  257.000000  262.000000  261.000000  261.000000   
mean    19.589771    3.016832    0.645914    0.377863    1.743295    0.739464   
std      9.302238    1.398981    0.479168    0.485781    1.119411    0.439771   
min      2.360000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.137500    2.000000    0.000000    0.000000    1.000000    0.000000   
50%     17.795000    3.000000    1.000000    0.000000    2.000000    1.000000   
75%     24.457500    3.610000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  262.000000  262.000000  
mean     2.599237    0.173595  
std      0.980499    0.107647  
min      1.000000    0.035638  
25%      2.000000    0.129616  
50%      2.000000    0.156661  
75%      3.000000    0.194900  
max      6.000000    1.271186

## StandardScaler

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc = StandardScaler()


In [53]:
df_sc = sc.fit_transform(data)

In [54]:
df_transform_sc=pd.DataFrame(df_sc)

In [55]:
df_transform_sc.describe().round() #평균이 0, 분산이 1로 바뀜

0      1      2      3      4      5      6
count  262.0  257.0  262.0  261.0  261.0  262.0  262.0
mean    -0.0   -0.0    0.0   -0.0    0.0   -0.0   -0.0
std      1.0    1.0    1.0    1.0    1.0    1.0    1.0
min     -2.0   -1.0   -1.0   -2.0   -2.0   -2.0   -1.0
25%     -1.0   -1.0   -1.0   -1.0   -2.0   -1.0   -0.0
50%     -0.0    1.0   -1.0    0.0    1.0   -1.0   -0.0
75%      1.0    1.0    1.0    1.0    1.0    0.0    0.0
max      3.0    1.0    1.0    1.0    1.0    3.0   10.0

## PCA

In [56]:
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA

In [57]:
data_trans.shape

(262, 7)

In [61]:
trans = PCA(n_components=5)

# transform the data
X_dim = trans.fit_transform(data_trans)

# summarize data after the transform
print(X_dim[:5, :])

[[-2.61051936 -1.20638218 -0.5039908   0.04675911  0.8850312 ]
 [-9.17793447 -1.59531464  0.86212017 -0.25732424 -0.11052262]
 [ 1.46930824 -1.30400489  0.25786656 -0.37130831  0.01698502]
 [ 4.07242268 -1.12516399 -0.8611334  -0.5964698   0.15026548]
 [ 5.095536   -1.21106267  1.00187714  0.35914671  0.77259944]]


In [59]:
df_X_dim=pd.DataFrame(X_dim)

In [60]:
df_X_dim.describe().round()

0      1      2      3
count  262.0  262.0  262.0  262.0
mean    -0.0   -0.0    0.0    0.0
std      9.0    1.0    1.0    0.0
min    -17.0   -2.0   -2.0   -1.0
25%     -6.0   -1.0   -1.0   -0.0
50%     -2.0   -0.0   -0.0   -0.0
75%      5.0    1.0    0.0    0.0
max     31.0    2.0    3.0    1.0

## Regression Feature Selection:

In [82]:
from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [83]:
fs = SelectKBest(score_func=f_regression, k=4)

In [84]:
# apply feature selection
X_selected = fs.fit_transform(data_trans, y)
print(X_selected.shape)

(262, 4)


In [85]:
df_X_selected = pd.DataFrame(X_selected)

In [86]:
df_X_selected.describe()

0           1           2           3
count  262.000000  262.000000  262.000000  262.000000
mean    19.589771    1.744275    2.599237    0.173595
std      9.302238    1.117377    0.980499    0.107647
min      2.360000    0.000000    1.000000    0.035638
25%     13.137500    1.000000    2.000000    0.129616
50%     17.795000    2.000000    2.000000    0.156661
75%     24.457500    3.000000    3.000000    0.194900
max     50.810000    3.000000    6.000000    1.271186